# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{auditor}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Your Name"]
  s.date = %q{2011-07-10}
  s.email = %q{you@email.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/models/auditor/auditor_log.rb",
    "config/routes.rb",
    "lib/acts_as_widget/base.rb",
    "lib/application_controller.rb",
    "lib/application_helper.rb",
    "lib/auditor.rb",
    "lib/engine.rb",
    "lib/rails/generators/auditor/auditor_generator.rb",
    "lib/rails/generators/auditor/templates/initializer.rb",
    "lib/rails/generators/auditor/templates/migration.rb",
    "lib/rails/generators/auditor/templates/schema.rb",
    "lib/rails/railties/tasks.rake"
  ]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Provides audit logging to a database of controller requests.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

